# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run-tests-with-bitrise-build-cache:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install Bazelisk"
          command: |
            #!/usr/bin/env bash
            set -euxo pipefail

            sudo curl -Lo /usr/local/bin/bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
            sudo chmod +x /usr/local/bin/bazelisk
            sudo ln -s /usr/local/bin/bazelisk /usr/local/bin/bazel
            bazel --version
      - run:
          name: "Enable Build Cache for Bazel"
          command: |
            #!/usr/bin/env bash
            set -euxo pipefail

            # download Bitrise Build Cache CLI
            curl -sSfL 'https://raw.githubusercontent.com/bitrise-io/bitrise-build-cache-cli/main/install/installer.sh' | sh -s -- -b /tmp/bin -d

            # run the CLI to enable Bitrise build cache for Bazel
            /tmp/bin/bitrise-build-cache enable-for bazel
      - run:
          name: "bazel test //..."
          command: |
            bazel test //...
      - run:
          name: "bazel build //..."
          command: |
            bazel build //...

  run-tests-without-build-cache:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install Bazelisk"
          command: |
            #!/usr/bin/env bash
            set -euxo pipefail
            
            sudo curl -Lo /usr/local/bin/bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
            sudo chmod +x /usr/local/bin/bazelisk
            sudo ln -s /usr/local/bin/bazelisk /usr/local/bin/bazel
            bazel --version
      - run:
          name: "bazel test //..."
          command: |
            bazel test //...
      - run:
          name: "bazel build //..."
          command: |
            bazel build //...

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - run-tests-with-bitrise-build-cache
      - run-tests-without-build-cache